### ISSUE TITLE
Implement widget testing?

### ISSUE THREAD

**Issue by zaralockheart** [jonsamwell/dart_gherkin#12]
Hi, I would like to ask on how do I implement widget testing with this package.

Normal ways is to run with: 
```
testWidgets('scenarios', (WidgetTester tester) async {
    await tester.pumpWidget(WidgetToBeTested());
});
```

**Comment by jonsamwell** [comment]
Hi this is going to shortly be supported over in flutter_gherkin see https://github.com/jonsamwell/flutter_gherkin/issues/101
