### ISSUE TITLE
Interpolate scenario outline names

### ISSUE THREAD

**Issue by irundaia** [jonsamwell/dart_gherkin#19]
Hi,

I was playing around with gherkin, in particular with scenario outlines and tagging a set of examples.
Suppose I've got a scenario outline like:

```gherkin
  Scenario Outline: The user clicks <n> times.
    Given The counter shows a count of 0
    When The user clicks <n> times
    Then The counter shows a count of <n>
  @smoke
  Examples:
    | n  |
    | 0  |
    | 1  |
  Examples:
    | n  |
    | 42 |
```

When parsing this outline, the scenarios get the following names:

Example | Name
---------|---------
0 | The user clicks <n> times. Examples: (1)
1 | The user clicks <n> times. Examples: (2)
42 | The user clicks <n> times. Examples: (1)

To me this is confusing, I would have expected the `n` variable to be interpolated in the scenario name as well. (In particular, my build server is unable to differentiate between the `0` and `42` examples. I would have expected something along the lines of:

Example | Name
---------|---------
0 | The user clicks 0 times. Examples: (1)
1 | The user clicks 1 times. Examples: (2)
42 | The user clicks 42 times. Examples: (1)

Would you be open to a pull request that adds this interpolation?

**Comment by jonsamwell** [comment]
You can given the example a name after the ':' which would contextualise
the example values. For instance

```
Scenario Outline: The user clicks <n> times.
    Given The counter shows a count of 0
    When The user clicks <n> times
    Then The counter shows a count of <n>
  @smoke
  Examples: Normal clicks
    | n |
    | 0 |
    | 1 |
  Examples: Edge cases
    | n |
    | 42 |
```

You are welcome to send through a pr though.  I think the difficulty comes
when you have many example parameters that span more than one step.  How
would this scenario be handled?

**Comment by irundaia** [comment]
I have to admit that I did not know that it was possible to name the examples blocks. That would help indeed.

I don't think a parameter spanning multiple steps would be affected by the proposed change. I would leave the interpolation of the steps the way it is now.

Regarding a large number of parameters, it would be up to the writer of the feature to decide whether they would include all of them in the scenario name/description or not. I would at least keep the way the scenario name is interpolated consistent with the way steps are interpolated.

So the following scenario

```gherkin
Scenario Outline: Some scenario with the following parameters <n0>, <n1>, <n5>.
  Given System is setup with <n0> thingamajigs
  When <n1> is used
  Then <n3> does something
  And Something goes on with <n2>
  And Something goes on with <n4>
  And Something goes on with <n5>
Examples: Default
| n0 | n1 | n2 | n3 | n4 | n5 |
| 0  | 1  | 2  | 3  | 4  | 5  |
```
 
would be expanded into:
```gherkin
Scenario Outline: Some scenario with the following parameters 0, 1, 5. Examples: Default (1)
  Given System is setup with 0 thingamajigs
  When 1 is used
  Then 3 does something
  And Something goes on with 2
  And Something goes on with 4
  And Something goes on with 5
```

I'll try to come up with a PR tomorrow, I think it would then become clear what the impact of this change would be.

**Comment by jonsamwell** [comment]
Ah, I see what you mean now.  You want to interpolate parameters in the title.  Yes a PR for that would be great!
