### ISSUE TITLE
Null-Safety

### ISSUE THREAD

**Issue by OndrejKunc** [jonsamwell/dart_gherkin#21]
Hi,
thanks for the great library!
Do you have any plans for supporting the new null-safety feature?  I started to migrate my own package to null-safety which uses gherkin as a `dev_dependency`. Since gherkin is not migrated yet, I have to use `--no-sound-null-safety` flag when running tests. It makes debugging the tests difficult because I am not able to pass this flag to the VSCode `launch.json` or to the `Debug|Run` buttons in the IDE. The workaround is to put `// @dart=2.9` comment at the top of the test entry point.
It is no big deal since it is just `dev_dependency` which is not blocking the actual null-safety migration, but it would be nice to have sound null safety eventually.

**Comment by jonsamwell** [comment]
Yeah, I haven't really looked into null safety yet for dart but looks much like what you would expect.  The library will support it I have just got to get the time to do it.  Happy for a PR if you are able.

**Comment by damondouglas** [comment]
First, thank you for this really great work.

It seems that the options are:

1.  Refactor the glob package out of this repository
or
2. wait until test to upgrade the analyzer package

I arrived at the aforementioned options by simply modifying `pubspec.yaml` to:

```yaml
dependencies:
  path: ^1.8.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
  matcher: ^0.12.10-nullsafety.3

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
```

 but received after invoking `dart migrate`:

```
Migrating ... dart_gherkin

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[---------------------------------------------------------------------------------------------------------------------------------------/]Bad state: Error: package has unmigrated dependencies.

Before migrating your package, we recommend ensuring that every library it
imports (either directly or indirectly) has been migrated to null safety, so
that you will be able to run your unit tests in sound null checking mode.  You
are currently importing the following non-null-safe libraries:

  package:glob/glob.dart
  package:glob/src/ast.dart
  package:glob/src/io.dart
  package:glob/src/io_export.dart
  package:glob/src/list_tree.dart
  package:glob/src/parser.dart
  package:glob/src/utils.dart

Please upgrade the packages containing these libraries to null safe versions
before continuing.  To see what null safe package versions are available, run
the following command: `dart pub outdated --mode=null-safety`.

To skip this check and try to migrate anyway, re-run with the flag
`--skip-import-check`.
```

Then I tried to add the glob nullsafety package:

```
glob: ^2.0.0-nullsafety.0
```

But when running `pub upgrade`, I received:

```
Because test >=1.16.0-nullsafety.10 depends on analyzer >=0.36.0 <0.42.0 which depends on glob ^1.0.3, test >=1.16.0-nullsafety.10 requires glob ^1.0.3.
So, because gherkin depends on both glob ^2.0.0-nullsafety.0 and test ^1.16.0-nullsafety.13, version solving failed.
```

**Comment by jonsamwell** [comment]
@damondouglas many thanks for looking at this it is really helpful.  Do you think we could do it with mix null safety dependencies or is it all or nothing?

This is next on my list after I get the flutter_gherkin working with the new integration _test package

**Comment by damondouglas** [comment]
Thank you for replying so quickly.  If I read the results from both the dart migrate output and the pub upgrade output, it seems to me an all or nothing thing.  

I think we can't predict or know when any of the chain of dependencies around the glob library will resolve.  What I mean is, we can't predict when analyzer will update its dependency of glob, etc.  One idea is to simply post an issue to the respective pub libraries to make everyone is pointing to the nullsafe glob library.

Another option is to roll our sleeves up and do the business of refactoring out the glob library.  The following is more details around this refactoring option.

Pardon I haven't looked in full detail into the usage of the glob library.  What I would be worried about is if one were to refactor it out, would it break cases that weren't considered in the test coverage.  If you think there is sufficient test coverage, I would be happy to try my hand at refactoring out the glob library and do this as a pull request.

**Comment by jonsamwell** [comment]
Thanks for this extra info.

The glob library is used to find the `.feature` files from the paths provided, (see https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/configuration.dart#L19 & https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/test_runner.dart#L42).  There is pretty decent test coverage in this library so you shouldn't break anything without knowing.  I think this would have to be marked as a breaking change.

If you can find a decent way of refactoring this out I would be happy for you to do this.

**Comment by damondouglas** [comment]
Good day, @jonsamwell .  I'll be happy to!  The output of my refactoring will be:

- replace the `glob` dependency with a `src/glob` internal library.
- upgrade SDK version and pubspec dependencies for nullspec compliant packages (`pub upgrade` and `dart migrate` passes)
- add GitHub actions to run `pub run test` on push to a repo branch

**Comment by damondouglas** [comment]
Hello @jonsamwell, I wanted to check in with you to let you my progress.  When I resolved the issue with `pubspec.yaml` and the version clashing around the `glob` library, it allowed me to start using the `dart migrate` tool.  When using this tool, it began to reveal many null safety issues in the codebase.  I began then systematically changing the code according to its suggestion.  Yet, I found that I was making judgement calls on code I didn't write or know the intent.  There, I have the following recommendation.  The goal of my efforts was originally to solve the null-safety compatibility.  I see now this effort is accomplished in multiple parts where the first is to refactor out the `glob` dependency.  I'm wondering if these milestones now make more sense.

1.  Refactor out the `glob` dependency, independent of null-safety.  The output of this milestone is that `pub run test` passes.
2. Upgrade SDK version and pubspec dependencies for null safe compliant packages
3. Refactor codebase to be null safe according to suggestions from `dart migrate`

As far as 1 above, I can do myself.  3 above would need to involve you.  For this I'm open to doing a pair programming session which I think would be fun.  Or, perhaps if you'd like to tackle it on your own, I'm ok with that too.

Given what I wrote here, would you like me to tackle 1 above?

**Comment by jonsamwell** [comment]
@damondouglas sorry for the slow response.

Your last comment sounds good.  Happy for you to refactor the glob dependency out.  How do you plan to do this and replace the functionality.

Let's get that first bit done first then move onto the next two.  

It would be good it you could use https://github.com/jonsamwell/dart_gherkin/tree/code_gen_changes as your base branch as that has some pending changes in that I will publish shortly to support flutter_gherkin using integration_test rather than flutter_driver.

Many thanks for your help with this!  I'm sure I could find a bit of time for pair programming!

**Comment by damondouglas** [comment]
Thank you @jonsamwell I'll branch from https://github.com/jonsamwell/dart_gherkin/tree/code_gen_changes and try to accomplish 1 to refactor out the glob dependency.  My strategy is to pattern the constructor and method signatures used by this codebase with zero state returns.  Then I'll run the tests that exist in the codebase and make sure they break.  What I mean by zero state returns is the following.  If a method for example, returns a list, then initially the refactoring will return an empty list.  If a return type is a bool, make it false; string is an empty string, int is 0, etc.  That way I will have established that at least the structure of the constructors, property types and methods are established.  Breaking tests will tell me that I have a method to measure against progress.  Then I will incrementally fill out the details of the methods and property states of the glob data structures until the tests pass.

**Comment by damondouglas** [comment]
Good day, @jonsamwell I started this journal so you can watch my progress.  https://github.com/damondouglas/dart_gherkin/discussions/1

What I found odd is that when I replaced the glob dependency with a skeleton one that only had the constructor and method signatures, the test output was the exact same.  You can see the output referenced in the discussion I linked here.  Did I do something wrong you think?

**Comment by jonsamwell** [comment]
@damondouglas sorry there is a failing test on that branch I will fix it now for you

**Comment by jonsamwell** [comment]
Finally migrated in v2.0.0!

**Comment by damondouglas** [comment]
So awesome!  I have a capstone project where this library will be really helpful for me.

**Comment by jonsamwell** [comment]
Glad it helps, I'll be sorting out null-safety for `flutter_gherkin` in the next week.
