### ISSUE TITLE
Multiline strings to support YAML format

### ISSUE THREAD

**Issue by ervuks** [jonsamwell/dart_gherkin#23]
I have a use case where I would like to pass YAML in a multiline string and it would be converted to JSON (YAML is used for simplicity to write it). 
Example:
```
@multilineYaml
Feature: Multiline string YAML example
  Scenario: YAML scenario
    Given I can convert YAML to JSON structure
  """
  - name: YAML test
    type: simple_convertion
    value: 100
    conditions:
      - type: convertion
        value: Convertion value
  """
```
After multiline has been read, YAML is modified and the output now looks like this and from here it can't be correctly read with Dart: 
```
- name: YAML test
type: simple_convertion
value: 100
conditions:
- type: convertion
value: Convertion value
```

Point of code to check: 
https://github.com/jonsamwell/dart_gherkin/blob/45acf80426e94a4eb39f31cbe062ef26ea8ecde4/lib/src/gherkin/runnables/multi_line_string.dart#L23

&&

https://github.com/jonsamwell/dart_gherkin/blob/master/lib/src/gherkin/syntax/text_line_syntax.dart#L25

I was wondering if it's possible to put a flag or member property that would not perform trimming?

**Comment by jonsamwell** [comment]
Should be fixed in v2.0.0 thanks to a PR by @tshedor
