### ISSUE TITLE
French keyword "Lorsqu'il" makes parser crash

### ISSUE THREAD

**Issue by kchiron** [jonsamwell/dart_gherkin#29]
Hi!
We write our gherkin scenarios in full french - keywords included - and we spotted that the keyword `Lorsqu'` makes the parser crash with this error: `Unknown runnable child given to Scenario 'TextLineRunnable'`

When we replace it with `Lorsque il`, everything works fine. Example below:
![Capture d’écran 2021-02-26 à 18 14 11](https://user-images.githubusercontent.com/3019694/109335409-484bfe00-7862-11eb-88a6-ea453bdde9af.png)
![Capture d’écran 2021-02-26 à 18 14 35](https://user-images.githubusercontent.com/3019694/109335413-4aae5800-7862-11eb-8c25-ef0125339740.png)

We set up the `featureDefaultLanguage` to `fr` and nothing changed. We checked that this word was a part of the gherkin dictionary and so it is: https://raw.githubusercontent.com/cucumber/cucumber/80b282783dca20bbf3d32a8dd6c85abccf5bd70c/gherkin/gherkin-languages.json

For the meantime we will use "Lorsque il" instead of "Lorsqu'il" but it would be great if we could use this keyword 😃.

I tried to dive into the code to find out why this keyword causes error (I'm not very at my ease with dart but maybe it can help you) and I found that steps seem to be parsed twice, and at the second round, the line `Lorsqu'il va acheter sa baguette` is not considered as a `RunnableBlock`. Indeed condition `runnable is RunnableBlock` is false with the use of `Lorsqu'` keyword and true when we use `Lorsque` keyword. So, instead of continue parsing the feature file with `_parseBlock()` method, program jumps directly to `parentBlock.addChild(runnable)` and this jump raises an error.

I used your example repo to illustrate my issue 😄: [https://github.com/kchiron/french_example](https://github.com/kchiron/french_example). You can directly run tests within the example folder.

Thank you in advance for your help!

**Comment by jonsamwell** [comment]
Fixed in v2.0.0 👍
