### ISSUE TITLE
Need an extra maintainer?

### ISSUE THREAD

**Issue by tshedor** [jonsamwell/dart_gherkin#34]
Hey @jonsamwell I hope this isn't too forward. I know maintaining OS projects is tough, and it's hard when it's just you doing it. If you'd like an extra hand, I'd be happy to help as a maintainer of this repo and/or flutter_gherkin. I couldn't find your contact info quickly; if you'd like to have a chat please drop me a line at tshedor [at] greenbits.com

**Comment by jonsamwell** [comment]
Hi @tshedor I'll email you 👍
