### ISSUE TITLE
Support Gherkin Feature/Scenario descriptions

### ISSUE THREAD

**Issue by Moyubori** [jonsamwell/dart_gherkin#40]
Hi! I've been using this package to run and generate reports for my gherkin tests. I noticed that the description lines are either ignored (feature description) or treated as a syntax error (scenario description) by `flutter_gherkin`. I'm using `JsonReporter` to generate test report json files, that I then convert to HTML reports, but it seems that the `description` fields in `JsonFeature` and `JsonScenario` classes are hardcoded to always be empty strings.

Are there any plans to support handling descriptions? If not, are there any workarounds I could use, to automatically include descriptions in my reports?

**Comment by tshedor** [comment]
@Moyubori descriptions are supported when indented (referencing [this example on Gherkin's documentation](https://cucumber.io/docs/gherkin/reference#background)):

```gherkin
# Good:
Feature: Feature name
  This feature tests taps and swipes

# Bad:
Feature: Feature name
This feature tests taps and swipes
```

**Comment by jonsamwell** [comment]
Scenarios can now contain descriptions in v3.1.0
