### ISSUE TITLE
Comments in data tables

### ISSUE THREAD

**Issue by russell-sf** [jonsamwell/dart_gherkin#6]
Can I do something like this?

```
Given the following users exist:
  | name   | email                        |
  | Aslak   | aslak@cucumber.io | # some comment
  | Julien  | julien@cucumber.io |  # some comment
  | Matt    | matt@cucumber.io  |  # some comment
```

Gherkin parser doesn't like it. Is this even valid gherkin?

**Comment by jonsamwell** [comment]
Yes, I just tried this in CucumberJS and it is supported (note that the comment is not included in the table data given to the step).  So we should probably support this.

I've set aside sometime this weekend to get this and https://github.com/jonsamwell/flutter_gherkin/issues/42 sorted for you.

Jon

**Comment by jonsamwell** [comment]
Now fixed in the latest release
