### ISSUE TITLE
Step with less input parameters incorrectly used

### ISSUE THREAD

**Issue by MarkOSullivan94** [jonsamwell/dart_gherkin#66]
Currently having an issue where the wrong step is selected when I'm trying to run my gherkin tests.

### Steps

I have two `And` steps for my gherkin tests:

1. `shop {string} provided a shop log on {word} at UTC time {string}`

2. `shop {string} provided a shop log on {word}`

#### Scenario 1

Whenever I run my gherkin tests which has the following: 

`And the shop "Gherkin Shop" provided a shop log on "Friday" at UTC time "01:00:00"`

The selected step is the second one instead of the first one.

#### Scenario 2

Whereas if I have the following `And` step

`the shop "Gherkin Shop" provided a shop log on "Friday"`

Then the only step which matches is `'shop {string} provided a shop log on {word}'`

### What's causing this

I went ahead and inspected the code which determines the step selection and found this located in `feature_file_runner.dart`.

```dart
final executable = _steps.firstWhereOrNull(
      (s) => s.expression.isMatch(step.debug.lineText),
);
```

### Potential solution

If we use this line of code instead, we can see that in the first Gherkin test scenario there would be 2 matching results.

`_steps.where((s) => s.expression.isMatch(step.debug.lineText)).toList()`

If we extend the accessibility of the `_expectParameterCount` variable for `StepDefinitionGeneric` so there's a getter within `ExecutableStep`, then we could check which step has more steps and always opt to using that step over the rest.

If they have the same number of steps, we could resort to the default behaviour of taking the first match.

### Temporary solution

I can reword the step to make it more unique which is fine for now but not ideal and it'd be nicer if this improvement can be made for a future version 🤞

**Comment by youssef-t** [comment]
Hello @MarkOSullivan94,

It's possible to use regular expressions to define the steps. In your case, you can define your steps using the end of line symbol ($) as following:
`RegExp(r'shop {string} provided a shop log on {word}$')`
`RegExp(r'shop {string} provided a shop log on {word} at UTC time {string}$')`

Generally speaking, you need to be aware not to add a trailing whitespace by mistake in your scenarios as the step definition expects the end of line and not a whitespace.

I hope that this suggestion will resolve the issue.

**Comment by MarkOSullivan94** [comment]
@youssef-t this resolved my issue! Thank you.
