### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by natanloterio** [jonsamwell/dart_gherkin#7]
Hi, I've just cloned the example `flutter-driver-demo`, but there are some classes unreachable.
Like:
- Given1WithWorld
- StepDefinitionConfiguration

![image](https://user-images.githubusercontent.com/2896563/70739092-d044f700-1cf4-11ea-9d0f-bfe27d1ed102.png)

**Comment by jonsamwell** [comment]
Hi

As the library relies on dart_gherkin you need to add that import too.


import 'package:gherkin/gherkin.dart';

See an example step

https://github.com/jonsamwell/dart_gherkin/blob/master/example/supporting_files/steps/given_the_characters.step.dart#L1

Also where is that example repository it is not one that I have done?

**Comment by natanloterio** [comment]
I just pushed a PR. 
Can you review it pls?

**Comment by jonsamwell** [comment]
That is not a repository controlled by myself.  Could you give me the link
and I'll take a look at it? From the code snippets you pasted above it
looks to be very out of date.

**Comment by natanloterio** [comment]
Sure =)
https://github.com/DK15/flutter-driver-demo/pulls

**Comment by jonsamwell** [comment]
Unfortunately that link is an outdated and pretty terrible example.

**Comment by natanloterio** [comment]
I see. Anyway, if you could provide an updated example, that would be great!

**Comment by jonsamwell** [comment]
Sure see the flutter_gherkin example https://github.com/jonsamwell/flutter_gherkin/tree/master/example/test_driver
