### ISSUE TITLE
Scenario Outline & Scenario in same feature file

### ISSUE THREAD

**Issue by Holloweye** [jonsamwell/dart_gherkin#9]
The library throws an exception when running a Scenario Outline and Scenario in the same file.

`Unhandled exception:
Exception: Unknown runnable child given to Scenario 'ScenarioRunnable'
#0      ScenarioRunnable.addChild (package:gherkin/src/gherkin/runnables/scenario.dart:33:9)
#1      ScenarioOutlineRunnable.addChild (package:gherkin/src/gherkin/runnables/scenario_outline.dart:28:15)
#2      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:119:21)
#3      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:108:15)
#4      GherkinParser._parseBlock (package:gherkin/src/gherkin/parser.dart:108:15)
#5      GherkinParser.parseFeatureFile (package:gherkin/src/gherkin/parser.dart:55:7)
<asynchronous suspension>
#6      GherkinRunner.execute (package:gherkin/src/test_runner.dart:47:43)
<asynchronous suspension>
#7      main (file:///.../app_test.dart:37:26)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)`

**Comment by jonsamwell** [comment]
Hi,

Does this happen no matter the order of the scenario / scenario outline?

**Comment by jonsamwell** [comment]
Fixed in version 1.1.6+3
